Name:           ros-hydro-pr2-plugs-actions
Version:        1.0.16
Release:        0%{?dist}
Summary:        ROS pr2_plugs_actions package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/pr2_plugs_actions
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-actionlib
Requires:       ros-hydro-actionlib-msgs
Requires:       ros-hydro-base-local-planner
Requires:       ros-hydro-checkerboard-pose-estimation
Requires:       ros-hydro-costmap-2d
Requires:       ros-hydro-cv-bridge
Requires:       ros-hydro-dynamic-reconfigure
Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-image-transport
Requires:       ros-hydro-joint-trajectory-action-tools
Requires:       ros-hydro-move-base-msgs
Requires:       ros-hydro-outlet-pose-estimation
Requires:       ros-hydro-pr2-arm-move-ik
Requires:       ros-hydro-pr2-common-action-msgs
Requires:       ros-hydro-pr2-controller-manager
Requires:       ros-hydro-pr2-controllers-msgs
Requires:       ros-hydro-pr2-image-snapshot-recorder
Requires:       ros-hydro-pr2-msgs
Requires:       ros-hydro-pr2-plugs-common
Requires:       ros-hydro-pr2-plugs-msgs
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-roscpp-serialization
Requires:       ros-hydro-rospy
Requires:       ros-hydro-rostest
Requires:       ros-hydro-sensor-msgs
Requires:       ros-hydro-smach
Requires:       ros-hydro-smach-ros
Requires:       ros-hydro-std-srvs
Requires:       ros-hydro-stereo-wall-detection
Requires:       ros-hydro-tf
Requires:       ros-hydro-tf-conversions
Requires:       ros-hydro-tf2-geometry-msgs
Requires:       ros-hydro-tf2-ros
BuildRequires:  ros-hydro-actionlib
BuildRequires:  ros-hydro-actionlib-msgs
BuildRequires:  ros-hydro-base-local-planner
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-checkerboard-pose-estimation
BuildRequires:  ros-hydro-costmap-2d
BuildRequires:  ros-hydro-cv-bridge
BuildRequires:  ros-hydro-dynamic-reconfigure
BuildRequires:  ros-hydro-geometry-msgs
BuildRequires:  ros-hydro-image-transport
BuildRequires:  ros-hydro-joint-trajectory-action-tools
BuildRequires:  ros-hydro-move-base-msgs
BuildRequires:  ros-hydro-outlet-pose-estimation
BuildRequires:  ros-hydro-pr2-arm-move-ik
BuildRequires:  ros-hydro-pr2-common-action-msgs
BuildRequires:  ros-hydro-pr2-controller-manager
BuildRequires:  ros-hydro-pr2-controllers-msgs
BuildRequires:  ros-hydro-pr2-image-snapshot-recorder
BuildRequires:  ros-hydro-pr2-msgs
BuildRequires:  ros-hydro-pr2-plugs-common
BuildRequires:  ros-hydro-pr2-plugs-msgs
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-roscpp-serialization
BuildRequires:  ros-hydro-rospy
BuildRequires:  ros-hydro-rostest
BuildRequires:  ros-hydro-sensor-msgs
BuildRequires:  ros-hydro-smach
BuildRequires:  ros-hydro-smach-ros
BuildRequires:  ros-hydro-std-srvs
BuildRequires:  ros-hydro-stereo-wall-detection
BuildRequires:  ros-hydro-tf
BuildRequires:  ros-hydro-tf-conversions
BuildRequires:  ros-hydro-tf2-geometry-msgs
BuildRequires:  ros-hydro-tf2-ros

%description
pr2_plugs_actions contains actions specific to plugging in the PR2 robot.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Mon Oct 20 2014 Devon Ash <dash@clearpathrobotics.com> - 1.0.16-0
- Autogenerated by Bloom

* Fri Oct 17 2014 Devon Ash <dash@clearpathrobotics.com> - 1.0.14-0
- Autogenerated by Bloom

* Tue Oct 14 2014 Devon Ash <dash@clearpathrobotics.com> - 1.0.13-0
- Autogenerated by Bloom

* Fri Oct 10 2014 Devon Ash <dash@clearpathrobotics.com> - 1.0.12-0
- Autogenerated by Bloom

* Wed Sep 17 2014 Devon Ash <dash@clearpathrobotics.com> - 1.0.9-0
- Autogenerated by Bloom

* Thu Sep 11 2014 Devon Ash <dash@clearpathrobotics.com> - 1.0.8-0
- Autogenerated by Bloom

* Mon Sep 08 2014 Devon Ash <dash@clearpathrobotics.com> - 1.0.4-0
- Autogenerated by Bloom

